spring:
  application:
    name: "Prueba tecnica"
  r2dbc:
    url: ${MYSQL_R2DBC_URL:r2dbc:mysql://localhost:3306/client}
    username: ${MYSQL_R2DBC_USER:admin}
    password: ${MYSQL_R2DBC_PASSWORD:admin}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/client
    user: ${MYSQL_R2DBC_USER:admin}
    password: ${MYSQL_R2DBC_PASSWORD:admin}
    locations: classpath:db/migration
    baseline-on-migrate: true
jwt:
  secret: "ESTOESSUPERSUPERSUPERSEGURAJwT1234567890!_oO"
  expiration: 3600
  refresh:
    expiration: 604800
authenticate:
  url: /auth
refresh:
  url: /auth/refresh
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  observations:
    key-values:
      application: ${spring.application.name:prueba-tecnica}
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true
    display-operation-id: true
    try-it-out-enabled: true
server:
  port: ${PORT:8085}

logging:
  level:
    com.tecnica.prueba: DEBUG